// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA64bQzuiDF-I8CzWgw8xR7rq-9mENSvA4',
    appId: '1:514236381215:web:fb8b44fd82ece988503d2a',
    messagingSenderId: '514236381215',
    projectId: 'iotdemo-a5feb',
    authDomain: 'iotdemo-a5feb.firebaseapp.com',
    databaseURL: 'https://iotdemo-a5feb-default-rtdb.firebaseio.com',
    storageBucket: 'iotdemo-a5feb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEUJ8_7TlSDhLWkFQgOu6N9noGtUl0fN4',
    appId: '1:514236381215:android:fc9c83033d4ba9ae503d2a',
    messagingSenderId: '514236381215',
    projectId: 'iotdemo-a5feb',
    databaseURL: 'https://iotdemo-a5feb-default-rtdb.firebaseio.com',
    storageBucket: 'iotdemo-a5feb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAD69ds5OCrgRm1W36wJzNmhZcnJRdXtko',
    appId: '1:514236381215:ios:c848ab0d0b79e895503d2a',
    messagingSenderId: '514236381215',
    projectId: 'iotdemo-a5feb',
    databaseURL: 'https://iotdemo-a5feb-default-rtdb.firebaseio.com',
    storageBucket: 'iotdemo-a5feb.appspot.com',
    iosClientId: '514236381215-ovrtpil0psc038398ed8c9cm6ds1abte.apps.googleusercontent.com',
    iosBundleId: 'org.sr.ledwifi.wifiLed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAD69ds5OCrgRm1W36wJzNmhZcnJRdXtko',
    appId: '1:514236381215:ios:c848ab0d0b79e895503d2a',
    messagingSenderId: '514236381215',
    projectId: 'iotdemo-a5feb',
    databaseURL: 'https://iotdemo-a5feb-default-rtdb.firebaseio.com',
    storageBucket: 'iotdemo-a5feb.appspot.com',
    iosClientId: '514236381215-ovrtpil0psc038398ed8c9cm6ds1abte.apps.googleusercontent.com',
    iosBundleId: 'org.sr.ledwifi.wifiLed',
  );
}
